application: auto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: media
- url: /static
  static_dir: static
  expiration: 0
- url: .*
  script: emapix.wsgi.application

libraries:
- name: django
  version: 1.5
- name: MySQLdb
  version: latest
- name: ssl
  version: latest
- name: PIL
  version: 1.1.7

builtins:
- django_wsgi: on

skip_files:
- ^\.git
- ^\.idea
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^libs/Django.*
- ^libs/django
- ^libs/MySQL
- ^libs/_mysql